### ISSUE TITLE
[Bug]: URL replacer doesn't work

### ISSUE THREAD

**Issue by ooker777** [Enveloppe/obsidian-enveloppe#359]
What does the text transformation to the URL mean? In my understanding it just replaces text in the filename. So I expect if you have a file `a.md`, and with the rule to replace `a` with `b`, then you get `b.md` as the output. But it doesn't work.

![](https://enveloppe.github.io/img/Plugin-2.png) 

Ultimately I want to avoid the `%` character in the filename to avoid [URIError: URI malformed](https://stackoverflow.com/q/7449588/3416774). But even enabling the _Encode to URI_ option it still isn't converted to `%25`.

v7.2.12

**Comment by Mara-Li** [comment]
Can't repro, the % is converted into %25 on my side ; and % is replaced using the link replacement.
Note: if you use uri encoding, the regex is applied AFTER the encoding.

**Comment by ooker777** [comment]
That's strange. Can you share your config? Mine is:
```json
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "dryRun": {
      "enable": false,
      "folderName": "github-publisher"
    },
    "tokenPath": "%configDir%/plugins/%pluginID%/env",
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "commitMessage": "[skip netlify] PUBLISHER",
      "name": ""
    },
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "obsidian",
    "defaultName": "docs",
    "rootFolder": "docs",
    "yamlFolderKey": "category",
    "frontmatterTitle": {
      "enable": true,
      "key": "filename"
    },
    "replaceTitle": [],
    "replacePath": [],
    "autoclean": {
      "includeAttachments": true,
      "enable": true,
      "excluded": [
        "docs/assets/favicon.svg",
        "docs/assets/favicon.ico",
        "docs/_data.yaml",
        "docs/_includes/og_image.jsx"
      ]
    },
    "folderNote": {
      "enable": true,
      "rename": "index.md",
      "addTitle": {
        "enable": true,
        "key": "title"
      }
    },
    "metadataExtractorPath": "",
    "subFolder": ""
  },
  "conversion": {
    "hardbreak": false,
    "dataview": true,
    "censorText": [
      {
        "entry": "/\\!\\[.*\\]\\(https:\\/\\/.*(youtube\\.com|youtu\\.be)\\/(.*).*\\)/",
        "replace": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/$2\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>",
        "after": true,
        "inCodeBlocks": true
      }
    ],
    "tags": {
      "inline": true,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": true,
      "unshared": false,
      "wiki": true,
      "slugify": "disable"
    }
  },
  "embed": {
    "attachments": true,
    "overrideAttachments": [],
    "keySendFile": [
      "image"
    ],
    "notes": true,
    "folder": "docs/assets/attachments",
    "convertEmbedToLinks": "keep",
    "charConvert": "->",
    "unHandledObsidianExt": [],
    "sendSimpleLinks": true,
    "forcePushAttachments": [],
    "useObsidianFolder": false
  },
  "plugin": {
    "shareKey": "share",
    "excludedFolder": [
      "Ξ Thiết lập"
    ],
    "copyLink": {
      "enable": true,
      "links": "https://kiếmtiền.quảcầu.cc/",
      "removePart": [
        "content",
        "index.md"
      ],
      "transform": {
        "toUri": true,
        "slugify": "disable",
        "applyRegex": [
          {
            "regex": "%",
            "replacement": "％"
          }
        ]
      }
    },
    "setFrontmatterKey": "Set"
  },
  "tabsId": "plugin-settings"
}
```
System info:
```
Obsidian version: v1.6.7
Installer version: v1.4.13
Operating system: Windows 10 Home Single Language 10.0.22631
Login status: logged in
Catalyst license: none
Insider build toggle: off
Live preview: off
Base theme: adapt to system
Community theme: Catppuccin v0.4.18
Snippets enabled: 2
Restricted mode: off
Plugins installed: 1
Plugins enabled: 1
1: Enveloppe v7.2.12
```

**Comment by Mara-Li** [comment]
Why you remplace % by %?  ^^'

**Comment by ooker777** [comment]
They are different characters actually: `%` vs `％`. It's to workaround the escaping character that uses the normal one (`%`). If you replace that with `a` and `b`, the problem persists.

**Comment by Mara-Li** [comment]
It works on my side with your configuration…
I use the command (toggle) in the configuration to create it. Maybe there is a bug with the auto copy link?
Strange it use the same settings/function…

**Comment by ooker777** [comment]
Hmm, I just realize that those options are only available when _Copy link_ is enable. Does that mean this whole section is just for copying the URL, not actually modifying the output filename? I use a sandbox vault and only install the plugin and import the setting, but in my output repo the filename still isn't converted.

Where do you get that screenshot? It doesn't seem to be from the console.

**Comment by Mara-Li** [comment]
I just copy / pasted XD
And Yes, it's only enabled when the copy-link option is enabled! And it doesn't change the name.
To change name, you need to use the filepath option.

It's just a shortcuts to quickly create a link using obsidian with your configuration, without relying on other plugin.

**Comment by ooker777** [comment]
Is the link automatically copied into the clipboard, or do I need to execute a command manually?

Is there a way to automatically replace the file name, like the option to replace the file content?

**Comment by Mara-Li** [comment]
1. It should be, and a command can be added
2. Yes, in filepath settings.

**Comment by ooker777** [comment]
> Yes, in filepath settings.

Stupid me 🤦 

The link isn't automatically copied into the clipboard to me

**Comment by Mara-Li** [comment]
For the commands, it needs to be enabled. Maybe the copy needs to have the settings for the commands enabled ? I need to test. Probably an error with && and ||
