### ISSUE TITLE
[FR]: Automatically add the "created" key with the file.ctime and add the "updated" key with the file.mtime

### ISSUE THREAD

**Issue by qwqw3qee** [Enveloppe/obsidian-enveloppe#364]
### Issue validation

- [X] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

When using cloud services to automatically deploy Quartz, the created time of notes will become the deployment time. Usually, it is necessary to manually add a field to frontmatter to mark the created time of notes (advanced, some blogs can also display article updated time by adding a field). Can the file's inherent properties be utilized to automatically create fields and add the file's creation and modification times when there are no relevant fields?

### What solution do you want to see ?

The function may be simliar to https://github.com/Enveloppe/obsidian-enveloppe/issues/242. 

### OS

Windows

### Plugin version

7.3.0

### Obsidian version & debug log

```bash session
Obsidian v1.6.7
```

**Comment by Mara-Li** [comment]
Out of the scope.
