### ISSUE TITLE
[FR]: 上传附件 能否将所有附件以当前笔记名为文件夹往里面进行存放呢？

### ISSUE THREAD

**Issue by news-epoch** [Enveloppe/obsidian-enveloppe#367]
### Issue validation

- [x] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

上传附件 能否将所有附件以当前笔记名为文件夹往里面进行存放呢？

### What solution do you want to see ?

![Image](https://github.com/user-attachments/assets/3455ef60-bf6b-49fe-8102-92735f3f9f8a)

### OS

Windows

### Plugin version

7.3.2

### Obsidian version & debug log

show debug log

**Comment by Mara-Li** [comment]
Issue not in English. Closed.
