### ISSUE TITLE
[Bug]: the internal links are missing part of the path in note and dataview, nav tree is fine

### ISSUE THREAD

**Issue by cbruyndoncx** [Enveloppe/obsidian-enveloppe#370]
### Issue validation

- [x] I checked the issue to prevent duplicate
- [x] I checked my configurations files and the documentation

### Command used

Upload all notes, Refresh all published notes

### Plugin version

7.4.0

### Describe the bug

I have the vault content structured into rootfolders and subfolders.
In the nav tree, this works fine,  but the internal links are not taking the full path into account.

It is as if a relative path string is generated, but missing the . Or a / too many at the start of the path

So in rootfolder 1, moc index file with dataview with link to file a in subfolders 1.1, has url domain/subfolder1.1/file a

My file a is a glossary, it has an item b  which Is defined in subfolder 1.2, the generated internal  link , no dataview,  is also domain/subfolder1.2/b

### How to reproduce ?

There is a 404 not found

### Minimal Reproducible Example

```markdown
Third brain dot tech

Kb ai rootfolder has moc click on ai glossary

Look for ai glossary in nav tree follow and click aider link
```

### Configuration

```JSON
{
  "github": {
    "branch": "v4",
    "automaticallyMergePR": true,
    "dryRun": {
      "enable": false,
      "folderName": "Www-enveloppe-dryrun"
    },
    "tokenPath": "%configDir%/plugins/%pluginID%/env",
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "commitMessage": "[PUBLISHER] Merge",
      "name": ""
    },
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "obsidian",
    "defaultName": "content",
    "rootFolder": "",
    "yamlFolderKey": "",
    "frontmatterTitle": {
      "enable": false,
      "key": "title"
    },
    "replaceTitle": [],
    "replacePath": [],
    "autoclean": {
      "includeAttachments": true,
      "enable": true,
      "excluded": []
    },
    "folderNote": {
      "enable": true,
      "rename": "index.md",
      "addTitle": {
        "enable": false,
        "key": "title"
      }
    },
    "metadataExtractorPath": ""
  },
  "conversion": {
    "hardbreak": true,
    "dataview": true,
    "censorText": [],
    "tags": {
      "inline": false,
      "exclude": [],
      "fields": [
        "status"
      ]
    },
    "links": {
      "internal": true,
      "unshared": false,
      "wiki": true,
      "slugify": "lower",
      "unlink": true
    }
  },
  "embed": {
    "attachments": false,
    "overrideAttachments": [],
    "keySendFile": [],
    "notes": true,
    "folder": "",
    "convertEmbedToLinks": "bake",
    "charConvert": "->",
    "unHandledObsidianExt": [],
    "sendSimpleLinks": false,
    "forcePush": false,
    "bake": {
      "textBefore": "_",
      "textAfter": "_\nSee {{url}} for more ..."
    }
  },
  "plugin": {
    "shareKey": "share",
    "excludedFolder": [
      "_FILEORGANIZER",
      "ABOUT",
      "CARINE",
      "Z_"
    ],
    "copyLink": {
      "enable": false,
      "links": "",
      "removePart": [],
      "transform": {
        "toUri": true,
        "slugify": "lower",
        "applyRegex": []
      }
    },
    "setFrontmatterKey": "Set",
    "saveTabId": false
  },
  "tabsId": "github-configuration"
}
```

### Relevant log output

```bash session

```

### OS

Android

### Anything else?

I just realize I have not tried on windows yert, will try tomorrow 

### Obsidian information

```bash session
Loading...



Nothing more
```

**Comment by cbruyndoncx** [comment]
debugging further revealed that the relative url in obsdian is correct ../sibling_dir/file, and as far as i can tell it is a quartz issue.
I can only see 2 levels working on thier site.

I also noticed similar issue on your gitub doc repo the wiki section links

**Comment by Mara-Li** [comment]
Good to know! Don't forget to create an issue so I can follow this to update the website. I choose to don't update often because the update methods is really not good and don't allow overriding many settings.
