### ISSUE TITLE
[Bug]: It show "Failed to load p;lugin: obsidian-mkdocs-publisher when I install the latest 7.5.0.

### ISSUE THREAD

**Issue by Rotion-lab** [Enveloppe/obsidian-enveloppe#374]
### Issue validation

- [x] I checked the issue to prevent duplicate
- [x] I checked my configurations files and the documentation

### Command used

Upload all notes

### Plugin version

7.5.0

### Describe the bug

As the error message mentioned in the title, and there is no option to configure when it's installed. 

### How to reproduce ?

1, Install Envelope 7.5.0, it show installed successfully
2. To enable it and show "Failed to load plugin: obsidian-mkdocs-publisher"
3. 3. There is no option to configure.

### Minimal Reproducible Example

```markdown
As mention above.
```

### Configuration

```JSON
No
```

### Relevant log output

```bash session

```

### OS

Windows

### Obsidian information

```bash session
Obsidian version 1.7.1

Windows 11
```

**Comment by Mara-Li** [comment]
It's a fresh new installation or a new update?
Do you have something in the console ? (Ctrl+MAJ+I)

**Comment by Mara-Li** [comment]
Okay, I can repro the bug. The fix will be done quickly

**Comment by amatya-aditya** [comment]
Hi Mara, I'm still experiencing that issue even with the latest update (7.5.1).

![Image](https://github.com/user-attachments/assets/93d1b657-64c7-4c6e-b133-acec8a3bea82)

**Comment by Mara-Li** [comment]
Strange. Will retry this morning.

**Comment by olabolola** [comment]
Having the same issue in macOS and obsidian version 1.8.0. "Failed to load plugin: obsidian-mkdocs-publisher".

**Comment by Mara-Li** [comment]
They was a problem with the manifest.json. It was deleted between the first fix and the second (7.5.2). I recreated the release that should fixe this problem, try to re-download the plugin or download the last zip in release

**Comment by Mara-Li** [comment]
Fixed in [release 5.7.2](https://github.com/Enveloppe/obsidian-enveloppe/releases/tag/7.5.2)

**Comment by Rotion-lab** [comment]
@Mara-Li  Will try, thx
